package commanderpepper.getpizza.models

import com.squareup.moshi.Json

data class RestaurantX(
        @Json(name = "apikey")
        val apikey: String,
        @Json(name = "average_cost_for_two")
        val averageCostForTwo: Int,
        @Json(name = "book_again_url")
        val bookAgainUrl: String,
        @Json(name = "book_form_web_view_url")
        val bookFormWebViewUrl: String,
        @Json(name = "cuisines")
        val cuisines: String,
        @Json(name = "currency")
        val currency: String,
        @Json(name = "deeplink")
        val deeplink: String,
        @Json(name = "establishment_types")
        val establishmentTypes: List<Any>,
        @Json(name = "events_url")
        val eventsUrl: String,
        @Json(name = "featured_image")
        val featuredImage: String,
        @Json(name = "has_online_delivery")
        val hasOnlineDelivery: Int,
        @Json(name = "has_table_booking")
        val hasTableBooking: Int,
        @Json(name = "id")
        val id: String,
        @Json(name = "include_bogo_offers")
        val includeBogoOffers: Boolean,
        @Json(name = "is_book_form_web_view")
        val isBookFormWebView: Int,
        @Json(name = "is_delivering_now")
        val isDeliveringNow: Int,
        @Json(name = "is_table_reservation_supported")
        val isTableReservationSupported: Int,
        @Json(name = "is_zomato_book_res")
        val isZomatoBookRes: Int,
        @Json(name = "location")
        val location: Location,
        @Json(name = "menu_url")
        val menuUrl: String,
        @Json(name = "mezzo_provider")
        val mezzoProvider: String,
        @Json(name = "name")
        val name: String,
        @Json(name = "offers")
        val offers: List<Any>,
        @Json(name = "opentable_support")
        val opentableSupport: Int,
        @Json(name = "photos_url")
        val photosUrl: String,
        @Json(name = "price_range")
        val priceRange: Int,
        @Json(name = "R")
        val r: R,
        @Json(name = "switch_to_order_menu")
        val switchToOrderMenu: Int,
        @Json(name = "thumb")
        val thumb: String,
        @Json(name = "url")
        val url: String,
        @Json(name = "user_rating")
        val userRating: UserRating
)